# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3924cd96a78a68c5befe0be8f0012f181c8b7fbf4475c3a60636c689e343fcf855d3e335bac440d4659a77666bc9caadbe8f3f91b20dc891d9119b94b61d035

test:
  secret_key_base: 8c295df56bb22b1212994d1c5e2632c1e264591ad6e529f0ce14a01d0d38584aa0ace41ba226d77fb52662d6312b781fd8ee7f36dd4c7e162e41f9ac028a145c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
